import Footer from '@/components/Footer'
import './globals.css'

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative min-'>
        {children}
        {/* footer */}
        <Footer/>
        </body>
    </html>
  )
}
