import Footer from '@/components/Footer'
import './globals.css'

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
}

export default function SearchLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* footer */}
       
        </body>
    </html>
  )
}
